### ISSUE TITLE
BigBrother and ParkourRewards on http://forums.gladiatormine.net/index.php?resources/

### ISSUE THREAD

**Issue by Driesboy** [EnderManiacsKingdom/GladiatorMine#1]
!!!!!! its my plugins

**Comment by matthew4444** [comment]
add the credits -.-

**Comment by Driesboy** [comment]
no remove i will upload if its ready to upload

**Comment by erkam2002** [comment]
matthew4444?

**Comment by erkam2002** [comment]
pls delete all and copy it all from genisys is better and i can add more features in genisys is already nether and enchanment

**Comment by Driesboy** [comment]
yes genisys is better

**Comment by Driesboy** [comment]
php7?

**Comment by erkam2002** [comment]
yes

**Comment by erkam2002** [comment]
can you make it i cant make it iam new on github (iam bad on Github) xD

**Comment by matthew4444** [comment]
NO REMOVING GLADIATORMINE!!!!!

**Comment by erkam2002** [comment]
No removing pls fork it from genisys

**Comment by matthew4444** [comment]
fork wht

**Comment by erkam2002** [comment]
Is better you have importet Gladiatormine from Imagicalmine but genisys is betzer import it pls from genisys

**Comment by matthew4444** [comment]
?

**Comment by matthew4444** [comment]
wht u want me to import

**Comment by erkam2002** [comment]
Copy

**Comment by matthew4444** [comment]
LOOK HERE https://github.com/EnderManiacsKingdom/GladiatorMine/blob/php7-0.14/NEED_TO_ADD_THESE_API'S.MD I TYPED THAT WHOLE THING WE NEED TO DO THIS NOW

**Comment by matthew4444** [comment]
WHAT FEATURES U WANT FROM GENYSIS ALSO AND WE NEED A GLADIATORMINE APP EXPECT IT WILL BE BASED FROM THE POCKETMINE APP IN THE PLAY STORE

**Comment by erkam2002** [comment]
Genisys have already nether and rnchantment

**Comment by matthew4444** [comment]
give me a min

**Comment by matthew4444** [comment]
https://github.com/EnderManiacsKingdom/GladiatorMine-Android

**Comment by matthew4444** [comment]
U ADD THE NETHER AND ENCHANTMENT PLZ. TELL ME WHEN UR DONE PLZ

**Comment by erkam2002** [comment]
Matthew pls deelete the src and copy it fr genisys i can it not iam new on github

**Comment by matthew4444** [comment]
no im making shoping cart ai,and im adding netherr and experance
